# Generated by Django 2.0.3 on 2018-03-18 17:01

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('territory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrib', django_mysql.models.DynamicField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territory.PollingStation')),
            ],
        ),
    ]
