# Generated by Django 2.0.3 on 2018-04-11 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voter', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='voter',
            name='operators',
            field=models.ManyToManyField(related_name='voters', to=settings.AUTH_USER_MODEL),
        ),
        
    ]
