# Generated by Django 2.0.3 on 2018-04-11 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voter', '0002_auto_20180411_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voter',
            options={'verbose_name': 'виборець', 'verbose_name_plural': 'виборці'},
        ),

    ]
