# Generated by Django 2.0.3 on 2018-04-11 18:53

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0004_auto_20180411_1852'),
    ]

    operations = [
      
    ]
