# Generated by Django 2.0.3 on 2018-04-11 18:54

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0005_auto_20180411_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='attrib',
            field=django_mysql.models.DynamicField(),
        ),
    ]
