# Generated by Django 2.0.3 on 2018-05-16 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter', '0006_auto_20180411_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='operators',
            field=models.ManyToManyField(null=True, related_name='voters', to=settings.AUTH_USER_MODEL),
        ),
    ]
