# Generated by Django 2.0.3 on 2018-03-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='stations',
            field=models.ManyToManyField(related_name='constituencies', to='territory.PollingStation'),
        ),
    ]
