# Generated by Django 2.0.3 on 2018-03-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0002_auto_20180329_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='address',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='pollingstation',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
