# Generated by Django 2.0.3 on 2018-04-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0003_auto_20180330_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constituency',
            name='description',
            field=models.CharField(blank=True, max_length=8192, null=True),
        ),
    ]
