# Generated by Django 2.0.3 on 2018-03-18 17:01

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('territory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'число'), (2, 'рядок')])),
                ('options', django_mysql.models.DynamicField()),
                ('stations', models.ManyToManyField(blank=True, to='territory.PollingStation')),
            ],
        ),
    ]
