# Generated by Django 2.0.3 on 2018-03-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20180318_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='status.Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.CharField(max_length=1024),
        ),
    ]
