# Generated by Django 2.0.3 on 2018-03-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20180318_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_static',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='stations',
            field=models.ManyToManyField(blank=True, related_name='statuses', to='territory.PollingStation'),
        ),
    ]
