# Generated by Django 2.0.3 on 2018-03-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_auto_20180319_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='is_static',
            new_name='_is_static',
        ),
    ]
