# Generated by Django 2.0.3 on 2018-03-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20180319_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='_is_static',
            new_name='is_static',
        ),
    ]
