# Generated by Django 2.0.3 on 2018-03-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_auto_20180320_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='is_static',
            field=models.NullBooleanField(default=True),
        ),
    ]
